name: Release

on:
  push:
    branches: "main"

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled
  DDEV_DEBUG: true

jobs:
  build:
    name: Build DDEV executables
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Build DDEV executables
        run: make windows_amd64

      - name: Generate artifacts
        run: ./.ci-scripts/generate_artifacts.sh ${{ github.workspace }}/artifacts

  sign-ddev-on-windows:
    name: Sign ddev.exe on Windows
    runs-on: [ self-hosted, windows-signer ]
    needs: build
    steps:
      - name: Sign windows ddev.exe
        shell: bash
        run: |
          set -x
          ls -lR "$(cygpath -u ${{ github.workspace }})"
          signtool sign "${{ github.workspace }}/artifacts/ddev.exe"


