name: Release

on:
  push:
    branches: "main"

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_CLI_EXPERIMENTAL: enabled
  DDEV_DEBUG: true
  JUNK: ${{ secrets.JUNK }}

jobs:
  create-cache:
    name: Create cache
    runs-on: ubuntu-20.04
    steps:
      - name: create a file or two
        run: mkdir -p junk && cd junk && touch one two three
      - uses: actions/cache@v2
        with:
          path: junk
          key: j1
      - name: "see what's there in source"
        run: ls -lR junk
      - name: restore it
        uses: actions/cache@v2
        with:
          path: junk2
          restore-keys: j1
          key: j1
      - name: "see what's there in restore"
        run: ls -lR junk2
      - name: create another file or two
        run: mkdir -p junk && cd junk && touch four five
      - uses: actions/cache@v2
        with:
          path: junk
          key: j1
      - name: restore after additional stuff
        uses: actions/cache@v2
        with:
          path: junk2
          restore-keys: j1
          key: j1
      - name: "see what's there in restore after new restore"
        run: ls -lR junk2

  build:
    name: Build DDEV executables
    runs-on: ubuntu-20.04

    steps:
      - name: Set up linux
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq nsis
          wget https://sourceforge.net/projects/nsis/files/NSIS%203/3.06.1/nsis-3.06.1.zip/download && sudo unzip -o -d /usr/share download && sudo mv /usr/share/nsis-3.06.1 /usr/share/nsis
          wget https://github.com/GsNSIS/EnVar/releases/latest/download/EnVar-Plugin.zip && sudo unzip -o -d /usr/share/nsis EnVar-Plugin.zip
          wget https://github.com/DigitalMediaServer/NSIS-INetC-plugin/releases/latest/download/INetC.zip && sudo unzip -o -d /usr/share/nsis/Plugins INetC.zip

      - uses: actions/checkout@v2
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Build DDEV executables
        run: make windows_install darwin_amd64 darwin_arm64

      - uses: actions/upload-artifact@v2
        with:
          name: ddev-windows-binaries
          path: .gotmp/bin/windows_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: ddev-macos-amd64
          path: .gotmp/bin/darwin_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: ddev-macos-arm64
          path: .gotmp/bin/darwin_arm64

  sign-ddev-on-windows:
    name: Sign ddev.exe on Windows
    runs-on: [ self-hosted, windows-signer ]
    needs: build
    steps:
      - name: remove any existing binaries
        shell: bash
        run: rm -f /c/tmp/*.exe
      - name: download ddev-windows-binaries
        uses: actions/download-artifact@v2
        with:
          name: ddev-windows-binaries
          path: "C:/tmp"
      - name: Sign windows ddev.exe
        shell: bash
        run: |
          set -x
          ls -l /c/tmp
          signtool sign "C:/tmp/ddev.exe" "C:/tmp/mkcert.exe" "C:/tmp/nssm.exe" "C:/tmp/winnfsd.exe" "C:/tmp/ddev_gen_autocomplete.exe"
      - name: Upload signed ddev-windows-binaries
        uses: actions/upload-artifact@v2
        with:
          name: ddev-windows-binaries
          path: "C:/tmp/*.exe"

  build-windows-installer-with-signed-ddev:
    name: Build the windows installer using the signed executables
    runs-on: ubuntu-20.04
    needs: sign-ddev-on-windows
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.*
      - name: Set up linux
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq nsis
          wget https://sourceforge.net/projects/nsis/files/NSIS%203/3.06.1/nsis-3.06.1.zip/download && sudo unzip -o -d /usr/share download && sudo mv /usr/share/nsis-3.06.1 /usr/share/nsis
          wget https://github.com/GsNSIS/EnVar/releases/latest/download/EnVar-Plugin.zip && sudo unzip -o -d /usr/share/nsis EnVar-Plugin.zip
          wget https://github.com/DigitalMediaServer/NSIS-INetC-plugin/releases/latest/download/INetC.zip && sudo unzip -o -d /usr/share/nsis/Plugins INetC.zip
      - name: remove any existing binaries
        shell: bash
        run: rm -f .gotmp/bin/windows_amd64/*.exe
      - name: download ddev-windows-binaries
        uses: actions/download-artifact@v2
        with:
          name: ddev-windows-binaries
          path: ".gotmp/bin/windows_amd64"
      - name: Make installer with signed binaries
        run: make windows_install
      - name: Upload unsigned ddev-windows-installer
        uses: actions/upload-artifact@v2
        with:
          name: ddev-windows-installer
          path: ".gotmp/bin/windows_amd64/ddev*.exe"

  sign-ddev-installer-on-windows:
    name: Sign ddev_windows_installer
    runs-on: [ self-hosted, windows-signer ]
    needs: build-windows-installer-with-signed-ddev
    steps:
      - name: remove any existing binaries
        shell: bash
        run: rm -f /c/tmp/*.exe
      - name: download ddev-windows-installer
        uses: actions/download-artifact@v2
        with:
          name: ddev-windows-installer
          path: "C:/tmp"
      - name: Sign ddev_windows_installer
        shell: bash
        run: signtool sign "C:/tmp/ddev_windows_installer*.exe"
      - name: Upload signed ddev-windows-installer
        uses: actions/upload-artifact@v2
        with:
          name: ddev-windows-installer
          path: "C:/tmp/ddev_*install*.exe"

  sign-ddev-on-macos:
    name: Sign and Notarize ddev on macOS
    runs-on: macos-latest
    needs: build
    steps:
      - name: "setup macOS"
        run: |
          brew install coreutils gnu-getopt jq
          pip3 install yq
      - uses: actions/checkout@v2
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.*
      - name: download ddev-macos-amd64
        uses: actions/download-artifact@v2
        with:
          name: ddev-macos-amd64
          path: ".gotmp/bin/darwin_amd64"
      - name: Sign and notarize binary
        env:
          DDEV_MACOS_SIGNING_PASSWORD: ${{ secrets.DDEV_MACOS_SIGNING_PASSWORD }}
          DDEV_MACOS_APP_PASSWORD: ${{ secrets.DDEV_MACOS_APP_PASSWORD }}
        run: |
          set -o errexit -o pipefail
          if [ -z "${DDEV_MACOS_SIGNING_PASSWORD}" ] ; then echo "DDEV_MACOS_SIGNING_PASSWORD is empty"; fi
          if [ -z "${DDEV_MACOS_APP_PASSWORD}" ] ; then echo "DDEV_MACOS_APP_PASSWORD is empty"; fi
          echo "Signing and notarizing .gotmp/bin/darwin_amd64/ddev ..."
          curl -s https://raw.githubusercontent.com/drud/signing_tools/master/macos_sign.sh | bash -s -  --signing-password="${DDEV_MACOS_SIGNING_PASSWORD}" --cert-file=certfiles/ddev_developer_id_cert.p12 --cert-name="Developer ID Application: DRUD Technology, LLC (3BAN66AG5M)" --target-binary=".gotmp/bin/darwin_amd64/ddev"
          curl -sSL -f https://raw.githubusercontent.com/drud/signing_tools/master/macos_notarize.sh | bash -s -  --app-specific-password=${DDEV_MACOS_APP_PASSWORD} --apple-id=accounts@drud.com --primary-bundle-id=com.ddev.ddev --target-binary=".gotmp/bin/darwin_amd64/ddev"
          ls -lR .gotmp/bin/darwin_amd64
      - name: Upload signed ddev-macos-amd64 binaries
        uses: actions/upload-artifact@v2
        with:
          name: ddev-macos-amd64
          path: .gotmp/bin/darwin_amd64
#      - name: Upload signed ddev-macos-arm64 binaries
#        uses: actions/upload-artifact@v2
#        with:
#          name: ddev-macos-arm64
#          path: .gotmp/bin/darwin_arm64

