name: Windows tests
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate set "debug_enabled"'
        required: false
        default: false

defaults:
  run:
    shell: bash

env:
  DDEV_DEBUG: true

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        webserver: [nginx-fpm]
        tests: [test]
        os: [ windows-2022 ]
        no-bind-mounts: ['true']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      DDEV_TEST_WEBSERVER_TYPE: ${{ matrix.webserver }}
      DDEV_NONINTERACTIVE: "true"
      DDEV_TEST_NO_BIND_MOUNTS: ${{ matrix.no-bind-mounts }}
      GOTEST_SHORT: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
#        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}


      - name: Run tests
        run: make test
      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: ddev-test-results-${{ matrix.webserver }}
          path: /tmp/testresults/
